# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='participants',
            field=models.ManyToManyField(to='encounters.Participant'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='rules',
            field=models.ManyToManyField(to='encounters.Rule'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='encounters.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.ManyToManyField(to='encounters.Rule'),
        ),
        migrations.AddField(
            model_name='point',
            name='allocation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encounters.Participant'),
        ),
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.CharField(default='N/A', max_length=128),
        ),
        migrations.AddField(
            model_name='rule',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encounters.Point'),
        ),
        migrations.AddField(
            model_name='game',
            name='rules',
            field=models.ManyToManyField(to='encounters.Rule'),
        ),
    ]
