# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='gamekeeper.Action')),
            ],
        ),
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_results', to='gamekeeper.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('actions', models.ManyToManyField(to='gamekeeper.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('actions', models.ManyToManyField(blank=True, to='gamekeeper.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('actions', models.ManyToManyField(blank=True, to='gamekeeper.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('allocation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='N/A', max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Rule')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Point')),
            ],
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='gamekeeper.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='gamekeeper.Player')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='gamekeeper.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Action')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Rule')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='triggers',
            field=models.ManyToManyField(through='gamekeeper.Trigger', to='gamekeeper.Action'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(blank=True, to='gamekeeper.Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='rules',
            field=models.ManyToManyField(blank=True, to='gamekeeper.Rule'),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_events', to='gamekeeper.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(to='gamekeeper.Player'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.ManyToManyField(blank=True, to='gamekeeper.Rule'),
        ),
        migrations.AddField(
            model_name='actionresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_results', to='gamekeeper.Event'),
        ),
        migrations.AddField(
            model_name='actionresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_results', to='gamekeeper.Player'),
        ),
        migrations.AddField(
            model_name='action',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Point'),
        ),
    ]
