# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:24
from __future__ import unicode_literals

from django.db import migrations


def import_scores(apps, schema_editor):
    Event = apps.get_model('gamekeeper', 'Event')
    Player = apps.get_model('gamekeeper', 'Player')
    Action = apps.get_model('gamekeeper', 'Action')
    Rule = apps.get_model('gamekeeper', 'Rule')


    for person in Person.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_scores),
    ]
