# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:28
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import gamekeeper.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0003_auto_20170822_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=enumfields.fields.EnumField(default='active', enum=gamekeeper.models.State, max_length=128),
            preserve_default=False,
        ),
    ]
