# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0003_auto_20170803_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='triggering_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Player'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='triggering_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_rules', to='gamekeeper.Action'),
        ),
    ]
