# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0004_auto_20170803_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='triggering_player',
        ),
        migrations.AddField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Action'),
        ),
        migrations.AddField(
            model_name='action',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='actions',
            field=models.ManyToManyField(to='gamekeeper.Action'),
        ),
    ]
