# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0005_auto_20170803_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rules',
        ),
        migrations.AddField(
            model_name='event',
            name='actions',
            field=models.ManyToManyField(to='gamekeeper.Action'),
        ),
        migrations.AddField(
            model_name='game',
            name='actions',
            field=models.ManyToManyField(blank=True, to='gamekeeper.Action'),
        ),
    ]
