# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamekeeper', '0006_auto_20170803_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamekeeper.Point'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_events', to='gamekeeper.Event'),
        ),
    ]
